# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(99, 99, 99);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.__frameBottom = QtWidgets.QFrame(self.centralwidget)
        self.__frameBottom.setMaximumSize(QtCore.QSize(16777215, 60))
        self.__frameBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__frameBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__frameBottom.setObjectName("__frameBottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.__frameBottom)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnGerarPessoa = QtWidgets.QPushButton(self.__frameBottom)
        self.btnGerarPessoa.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnGerarPessoa.setFont(font)
        self.btnGerarPessoa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGerarPessoa.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #dddddd;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(166, 166, 166)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: white;\n"
"    background-color: rgb(110, 110, 110)\n"
"}\n"
"")
        self.btnGerarPessoa.setObjectName("btnGerarPessoa")
        self.horizontalLayout.addWidget(self.btnGerarPessoa)
        self.gridLayout.addWidget(self.__frameBottom, 1, 0, 1, 1)
        self.__frameTop = QtWidgets.QFrame(self.centralwidget)
        self.__frameTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.__frameTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.__frameTop.setObjectName("__frameTop")
        self._Nome = QtWidgets.QLineEdit(self.__frameTop)
        self._Nome.setEnabled(True)
        self._Nome.setGeometry(QtCore.QRect(70, 28, 320, 30))
        self._Nome.setMinimumSize(QtCore.QSize(320, 30))
        self._Nome.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Nome.setFont(font)
        self._Nome.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Nome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Nome.setAlignment(QtCore.Qt.AlignCenter)
        self._Nome.setDragEnabled(False)
        self._Nome.setReadOnly(False)
        self._Nome.setObjectName("_Nome")
        self._Cep = QtWidgets.QLineEdit(self.__frameTop)
        self._Cep.setEnabled(True)
        self._Cep.setGeometry(QtCore.QRect(500, 362, 130, 30))
        self._Cep.setMinimumSize(QtCore.QSize(130, 30))
        self._Cep.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Cep.setFont(font)
        self._Cep.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Cep.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Cep.setAlignment(QtCore.Qt.AlignCenter)
        self._Cep.setDragEnabled(False)
        self._Cep.setReadOnly(False)
        self._Cep.setObjectName("_Cep")
        self._Cidade = QtWidgets.QLineEdit(self.__frameTop)
        self._Cidade.setEnabled(True)
        self._Cidade.setGeometry(QtCore.QRect(87, 362, 200, 30))
        self._Cidade.setMinimumSize(QtCore.QSize(200, 30))
        self._Cidade.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Cidade.setFont(font)
        self._Cidade.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Cidade.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Cidade.setAlignment(QtCore.Qt.AlignCenter)
        self._Cidade.setDragEnabled(False)
        self._Cidade.setReadOnly(False)
        self._Cidade.setObjectName("_Cidade")
        self._Email = QtWidgets.QLineEdit(self.__frameTop)
        self._Email.setEnabled(True)
        self._Email.setGeometry(QtCore.QRect(63, 232, 340, 30))
        self._Email.setMinimumSize(QtCore.QSize(340, 30))
        self._Email.setMaximumSize(QtCore.QSize(340, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Email.setFont(font)
        self._Email.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Email.setAlignment(QtCore.Qt.AlignCenter)
        self._Email.setDragEnabled(False)
        self._Email.setReadOnly(False)
        self._Email.setObjectName("_Email")
        self.label = QtWidgets.QLabel(self.__frameTop)
        self.label.setGeometry(QtCore.QRect(10, 32, 60, 20))
        self.label.setMinimumSize(QtCore.QSize(60, 20))
        self.label.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.__frameTop)
        self.label_8.setGeometry(QtCore.QRect(10, 235, 60, 20))
        self.label_8.setMinimumSize(QtCore.QSize(60, 20))
        self.label_8.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.__frameTop)
        self.label_11.setGeometry(QtCore.QRect(30, 365, 60, 20))
        self.label_11.setMinimumSize(QtCore.QSize(60, 20))
        self.label_11.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.__frameTop)
        self.label_12.setGeometry(QtCore.QRect(300, 365, 60, 20))
        self.label_12.setMinimumSize(QtCore.QSize(60, 20))
        self.label_12.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.__frameTop)
        self.label_13.setGeometry(QtCore.QRect(450, 365, 60, 20))
        self.label_13.setMinimumSize(QtCore.QSize(60, 20))
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(self.__frameTop)
        self.label_10.setGeometry(QtCore.QRect(40, 305, 70, 20))
        self.label_10.setMinimumSize(QtCore.QSize(70, 20))
        self.label_10.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self._Endereco = QtWidgets.QLineEdit(self.__frameTop)
        self._Endereco.setEnabled(True)
        self._Endereco.setGeometry(QtCore.QRect(110, 302, 500, 30))
        self._Endereco.setMinimumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Endereco.setFont(font)
        self._Endereco.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Endereco.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Endereco.setAlignment(QtCore.Qt.AlignCenter)
        self._Endereco.setDragEnabled(False)
        self._Endereco.setReadOnly(False)
        self._Endereco.setObjectName("_Endereco")
        self._CPF = QtWidgets.QLineEdit(self.__frameTop)
        self._CPF.setEnabled(True)
        self._CPF.setGeometry(QtCore.QRect(440, 28, 200, 30))
        self._CPF.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._CPF.setFont(font)
        self._CPF.setFocusPolicy(QtCore.Qt.NoFocus)
        self._CPF.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._CPF.setAlignment(QtCore.Qt.AlignCenter)
        self._CPF.setDragEnabled(False)
        self._CPF.setReadOnly(False)
        self._CPF.setObjectName("_CPF")
        self.label_2 = QtWidgets.QLabel(self.__frameTop)
        self.label_2.setGeometry(QtCore.QRect(390, 32, 60, 20))
        self.label_2.setMinimumSize(QtCore.QSize(60, 20))
        self.label_2.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.__frameTop)
        self.label_4.setGeometry(QtCore.QRect(310, 102, 80, 20))
        self.label_4.setMinimumSize(QtCore.QSize(80, 20))
        self.label_4.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self._Telefone = QtWidgets.QLineEdit(self.__frameTop)
        self._Telefone.setEnabled(True)
        self._Telefone.setGeometry(QtCore.QRect(480, 232, 180, 30))
        self._Telefone.setMinimumSize(QtCore.QSize(180, 30))
        self._Telefone.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Telefone.setFont(font)
        self._Telefone.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Telefone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Telefone.setAlignment(QtCore.Qt.AlignCenter)
        self._Telefone.setDragEnabled(False)
        self._Telefone.setReadOnly(False)
        self._Telefone.setObjectName("_Telefone")
        self.label_9 = QtWidgets.QLabel(self.__frameTop)
        self.label_9.setGeometry(QtCore.QRect(420, 235, 60, 20))
        self.label_9.setMinimumSize(QtCore.QSize(60, 20))
        self.label_9.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self._Altura = QtWidgets.QLineEdit(self.__frameTop)
        self._Altura.setEnabled(True)
        self._Altura.setGeometry(QtCore.QRect(111, 162, 80, 30))
        self._Altura.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Altura.setFont(font)
        self._Altura.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Altura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Altura.setAlignment(QtCore.Qt.AlignCenter)
        self._Altura.setDragEnabled(False)
        self._Altura.setReadOnly(False)
        self._Altura.setObjectName("_Altura")
        self.label_5 = QtWidgets.QLabel(self.__frameTop)
        self.label_5.setGeometry(QtCore.QRect(50, 165, 60, 20))
        self.label_5.setMinimumSize(QtCore.QSize(60, 20))
        self.label_5.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.__frameTop)
        self.label_6.setGeometry(QtCore.QRect(242, 165, 60, 20))
        self.label_6.setMinimumSize(QtCore.QSize(60, 20))
        self.label_6.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self._Estado = QtWidgets.QLineEdit(self.__frameTop)
        self._Estado.setEnabled(True)
        self._Estado.setGeometry(QtCore.QRect(360, 362, 80, 30))
        self._Estado.setMinimumSize(QtCore.QSize(80, 30))
        self._Estado.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Estado.setFont(font)
        self._Estado.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Estado.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Estado.setAlignment(QtCore.Qt.AlignCenter)
        self._Estado.setDragEnabled(False)
        self._Estado.setReadOnly(False)
        self._Estado.setObjectName("_Estado")
        self._Peso = QtWidgets.QLineEdit(self.__frameTop)
        self._Peso.setEnabled(True)
        self._Peso.setGeometry(QtCore.QRect(300, 162, 100, 30))
        self._Peso.setMinimumSize(QtCore.QSize(100, 30))
        self._Peso.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Peso.setFont(font)
        self._Peso.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Peso.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Peso.setAlignment(QtCore.Qt.AlignCenter)
        self._Peso.setDragEnabled(False)
        self._Peso.setReadOnly(False)
        self._Peso.setObjectName("_Peso")
        self.label_7 = QtWidgets.QLabel(self.__frameTop)
        self.label_7.setGeometry(QtCore.QRect(440, 165, 60, 20))
        self.label_7.setMinimumSize(QtCore.QSize(60, 20))
        self.label_7.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self._Sangue = QtWidgets.QLineEdit(self.__frameTop)
        self._Sangue.setEnabled(True)
        self._Sangue.setGeometry(QtCore.QRect(510, 162, 80, 30))
        self._Sangue.setMinimumSize(QtCore.QSize(80, 30))
        self._Sangue.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Sangue.setFont(font)
        self._Sangue.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Sangue.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Sangue.setAlignment(QtCore.Qt.AlignCenter)
        self._Sangue.setDragEnabled(False)
        self._Sangue.setReadOnly(False)
        self._Sangue.setObjectName("_Sangue")
        self._Nascimento = QtWidgets.QLineEdit(self.__frameTop)
        self._Nascimento.setEnabled(True)
        self._Nascimento.setGeometry(QtCore.QRect(400, 98, 150, 30))
        self._Nascimento.setMinimumSize(QtCore.QSize(150, 30))
        self._Nascimento.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Nascimento.setFont(font)
        self._Nascimento.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Nascimento.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Nascimento.setAlignment(QtCore.Qt.AlignCenter)
        self._Nascimento.setDragEnabled(False)
        self._Nascimento.setReadOnly(False)
        self._Nascimento.setObjectName("_Nascimento")
        self.label_3 = QtWidgets.QLabel(self.__frameTop)
        self.label_3.setGeometry(QtCore.QRect(130, 102, 60, 20))
        self.label_3.setMinimumSize(QtCore.QSize(60, 20))
        self.label_3.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self._Idade = QtWidgets.QLineEdit(self.__frameTop)
        self._Idade.setEnabled(True)
        self._Idade.setGeometry(QtCore.QRect(188, 98, 100, 30))
        self._Idade.setMinimumSize(QtCore.QSize(100, 30))
        self._Idade.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._Idade.setFont(font)
        self._Idade.setFocusPolicy(QtCore.Qt.NoFocus)
        self._Idade.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid grey;\n"
"")
        self._Idade.setAlignment(QtCore.Qt.AlignCenter)
        self._Idade.setDragEnabled(False)
        self._Idade.setReadOnly(False)
        self._Idade.setObjectName("_Idade")
        self.gridLayout.addWidget(self.__frameTop, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerador de Pessoas"))
        self.btnGerarPessoa.setText(_translate("MainWindow", "GERAR PESSOA"))
        self._Nome.setText(_translate("MainWindow", "NOME"))
        self._Cep.setText(_translate("MainWindow", "CEP"))
        self._Cidade.setText(_translate("MainWindow", "CIDADE"))
        self._Email.setText(_translate("MainWindow", "EMAIL"))
        self.label.setText(_translate("MainWindow", "Nome"))
        self.label_8.setText(_translate("MainWindow", "E-mail"))
        self.label_11.setText(_translate("MainWindow", "Cidade"))
        self.label_12.setText(_translate("MainWindow", "Estado"))
        self.label_13.setText(_translate("MainWindow", "Cep"))
        self.label_10.setText(_translate("MainWindow", "Endereço"))
        self._Endereco.setText(_translate("MainWindow", "ENDEREÇO"))
        self._CPF.setText(_translate("MainWindow", "CPF"))
        self.label_2.setText(_translate("MainWindow", "CPF"))
        self.label_4.setText(_translate("MainWindow", "Nascimento"))
        self._Telefone.setText(_translate("MainWindow", "TELEFONE"))
        self.label_9.setText(_translate("MainWindow", "Telefone"))
        self._Altura.setText(_translate("MainWindow", "ALTURA"))
        self.label_5.setText(_translate("MainWindow", "Altura"))
        self.label_6.setText(_translate("MainWindow", "Peso"))
        self._Estado.setText(_translate("MainWindow", "ESTADO"))
        self._Peso.setText(_translate("MainWindow", "PESO"))
        self.label_7.setText(_translate("MainWindow", "Sangue"))
        self._Sangue.setText(_translate("MainWindow", "TIPO"))
        self._Nascimento.setText(_translate("MainWindow", "DATA"))
        self.label_3.setText(_translate("MainWindow", "Idade"))
        self._Idade.setText(_translate("MainWindow", "IDADE"))
